name: pathfinder_sheet
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  elementary: ^3.0.0
  sembast: ^3.5.0+1
  flutter_svg: ^2.0.9
  go_router: ^13.1.0
  drift: ^2.13.2
  sqlite3_flutter_libs: ^0.5.19+1
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.13.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

